import asyncio
import logging
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Any, Literal, LiteralString, cast

from neo4j import AsyncGraphDatabase

from core.graph.models import (
    Case,
    CaseNode,
    Evidence,
    Hypothesis,
    Investigation,
    NodeBase,
    to_model,
)

logger = logging.getLogger("haive.store")

# A generic mutation callback: (event_type, node_id, node_type, payload). Using
# primitives keeps the store fully decoupled from core.events, the orchestrator
# wires this to bus.publish.
OnMutation = Callable[[str, str | None, str | None, dict], None]

@dataclass(frozen=True)
class EdgeSpec:
    """A birth edge for create_node: connects the NEW node to an EXISTING node.
    direction 'in'  -> (other)-[:edge_type]->(new)   e.g. Case -DERIVES-> new Hypothesis
    direction 'out' -> (new)-[:edge_type]->(other)   e.g. new Evidence -SUPPORTS-> Hypothesis
    """

    edge_type: str
    other_id: str
    direction: Literal["in", "out"] = "in"


class GraphStore:
    def __init__(self, uri: str, user: str, password: str, on_mutation: OnMutation | None = None):
        self._driver = AsyncGraphDatabase.driver(uri, auth=(user, password))
        self._on_mutation = on_mutation
        self._claim_lock = asyncio.Lock()  # serializes claims (see claim())

    async def close(self):
        await self._driver.close()

    # ---------- internal helper ----------

    def _emit(
        self,
        event_type: str,
        node_id: str | None = None,
        node_type: str | None = None,
        **payload,
    ) -> None:
        # Every graph mutation notifies. The store knows nothing about the bus; it
        # just calls the callback the orchestrator wired to bus.publish. This keeps
        # all coordination flowing through the medium (stigmergy).
        if self._on_mutation is not None:
            self._on_mutation(event_type, node_id, node_type, payload)

    def _to_model(self, neo4j_node) -> NodeBase:
        # a neo4j node carries both its properties and its labels
        props = dict(neo4j_node)
        label = list(neo4j_node.labels)[0]
        return to_model(label, props)

    # ---------- layer 1: generic primitives ----------

    async def create_node(
        self, node: NodeBase, label: str, edges: Sequence[EdgeSpec] = ()
    ) -> str:
        """Create a node AND its birth edges in ONE atomic Cypher statement, then
        emit (node_created first, then one edge_created per edge). Events therefore
        always announce a CONSISTENT state: the node exists with its edges, or not
        at all.

        Case-scoped nodes (CaseNode) MUST be born connected: passing no edges raises
        ValueError, which makes the no-orphans invariant hold by construction (the
        checker stays as defense in depth). InputSignal and the persistent nodes are
        exempt (they are not CaseNode). Also raises if an edge endpoint is missing
        (the whole statement matches endpoints first: nothing is created)."""
        if isinstance(node, CaseNode) and not edges:
            raise ValueError(
                f"{label} is case-scoped: it must be born connected (pass its birth edges)"
            )
        props = node.model_dump(mode="json")  # mode="json" serializes datetime to string
        # labels/edge_types come from the ontology (controlled), safe to interpolate
        match_parts = [f"(o{i} {{id: $oid{i}}})" for i in range(len(edges))]
        create_parts = [
            f"CREATE (o{i})-[:{e.edge_type}]->(n)"
            if e.direction == "in"
            else f"CREATE (n)-[:{e.edge_type}]->(o{i})"
            for i, e in enumerate(edges)
        ]
        query = ""
        if match_parts:
            query += "MATCH " + ", ".join(match_parts) + " "
        query += f"CREATE (n:{label} $props) " + " ".join(create_parts) + " RETURN n.id AS id"
        params: dict[str, Any] = {f"oid{i}": e.other_id for i, e in enumerate(edges)}
        async with self._driver.session() as session:
            result = await session.run(cast(LiteralString, query), props=props, **params)
            record = await result.single()
        if record is None:  # an endpoint did not exist: MATCH found nothing, nothing created
            raise ValueError(f"create_node({label}): an edge endpoint does not exist")
        self._emit("node_created", node_id=node.id, node_type=label)
        for e in edges:
            from_id, to_id = (e.other_id, node.id) if e.direction == "in" else (node.id, e.other_id)
            self._emit("edge_created", from_id=from_id, to_id=to_id, edge_type=e.edge_type)
        return node.id  # the id is generated by the model, not by Neo4j

    async def get_node(self, node_id: str) -> NodeBase | None:
        query = "MATCH (n {id: $id}) RETURN n"
        async with self._driver.session() as session:
            result = await session.run(query, id=node_id)
            record = await result.single()
            return self._to_model(record["n"]) if record else None

    async def update_node(self, node_id: str, changes: dict) -> None:
        query = "MATCH (n {id: $id}) SET n += $changes RETURN labels(n)[0] AS label"
        async with self._driver.session() as session:
            result = await session.run(query, id=node_id, changes=changes)
            record = await result.single()
        if record is not None:  # no row => the node did not exist; nothing mutated
            self._emit("node_updated", node_id=node_id, node_type=record["label"], changes=changes)

    async def create_edge(self, from_id: str, to_id: str, edge_type: str) -> None:
        # `edge_type` is an ontology type (controlled), so interpolating it is safe.
        query = cast(
            LiteralString,
            f"MATCH (a {{id: $from_id}}), (b {{id: $to_id}}) CREATE (a)-[:{edge_type}]->(b)",
        )
        async with self._driver.session() as session:
            await session.run(query, from_id=from_id, to_id=to_id)
        self._emit("edge_created", from_id=from_id, to_id=to_id, edge_type=edge_type)

    async def query_nodes(self, label: str, filters: dict) -> list[NodeBase]:
        where = " AND ".join(f"n.{k} = ${k}" for k in filters)
        query = f"MATCH (n:{label})"
        if where:
            query += f" WHERE {where}"
        query += " RETURN n"
        async with self._driver.session() as session:
            result = await session.run(cast(LiteralString, query), **filters)
            return [self._to_model(record["n"]) async for record in result]

    async def get_neighbors(
        self,
        node_id: str,
        edge_type: str,
        direction: str = "out",  # "out" or "in"
        target_label: str | None = None,
    ) -> list[NodeBase]:
        # follow one edge_type from node_id in the given direction
        target = f":{target_label}" if target_label else ""
        if direction == "out":
            pattern = f"(n {{id: $id}})-[:{edge_type}]->(m{target})"
        else:
            pattern = f"(n {{id: $id}})<-[:{edge_type}]-(m{target})"
        query = cast(LiteralString, f"MATCH {pattern} RETURN m")
        async with self._driver.session() as session:
            result = await session.run(query, id=node_id)
            return [self._to_model(record["m"]) async for record in result]

    # ---------- layer 2: domain queries ----------
    # These return concrete model types. The cast is safe because each query is
    # restricted to a single label/edge that yields exactly that type.

    async def get_refuting_evidence(self, hypothesis_id: str) -> list[Evidence]:
        return cast(
            list[Evidence],
            await self.get_neighbors(
                hypothesis_id, "CONTRADICTS", direction="in", target_label="Evidence"
            ),
        )

    async def get_supporting_evidence(self, hypothesis_id: str) -> list[Evidence]:
        return cast(
            list[Evidence],
            await self.get_neighbors(
                hypothesis_id, "SUPPORTS", direction="in", target_label="Evidence"
            ),
        )

    async def get_investigations_of_hypothesis(self, hypothesis_id: str) -> list[Investigation]:
        return cast(
            list[Investigation],
            await self.get_neighbors(
                hypothesis_id, "TESTS", direction="out", target_label="Investigation"
            ),
        )

    async def get_evidence_of_investigation(self, investigation_id: str) -> list[Evidence]:
        return cast(
            list[Evidence],
            await self.get_neighbors(
                investigation_id, "PRODUCES", direction="out", target_label="Evidence"
            ),
        )

    async def claim(self, label: str, filters: dict) -> NodeBase | None:
        """Find a `label` node with claim_state='pending' matching `filters`, mark it
        'claimed', and return it (or None if none is free). Serialized by _claim_lock,
        so claims happen one at a time and two concurrent drains never take the same
        node (independent of Neo4j's locking). The only place the claim is written."""
        where = " AND ".join(f"n.{k} = ${k}" for k in filters)
        query = f"MATCH (n:{label} {{claim_state: 'pending'}})"
        if where:
            query += f" WHERE {where}"
        query += " WITH n LIMIT 1 SET n.claim_state = 'claimed' RETURN n"
        async with self._claim_lock, self._driver.session() as session:
            result = await session.run(cast(LiteralString, query), **filters)
            record = await result.single()
        return self._to_model(record["n"]) if record else None

    async def complete(self, node_id: str) -> None:
        """Mark a claimed node finished (claim_state -> 'done'): success, never
        reclaimed."""
        query = "MATCH (n {id: $id}) SET n.claim_state = 'done'"
        async with self._driver.session() as session:
            await session.run(query, id=node_id)

    async def fail(self, node_id: str, max_attempts: int) -> str:
        """Record a failed attempt: increment `attempts`; back to 'pending' (retry)
        or, at max_attempts, 'failed' (terminal, never reclaimed). Emits node_updated
        ONLY when the node goes terminal: a retry is internal bookkeeping, a terminal
        failure is an outcome other roles react to (e.g. the Synthesizer closing a
        case whose last line failed). Returns the new state."""
        query = """
            MATCH (n {id: $id})
            WITH n, coalesce(n.attempts, 0) + 1 AS attempts
            SET n.attempts = attempts,
                n.claimed_by_agent_id = null,
                n.claim_state = CASE WHEN attempts >= $max THEN 'failed' ELSE 'pending' END
            RETURN n.claim_state AS state, labels(n)[0] AS label
        """
        async with self._driver.session() as session:
            result = await session.run(query, id=node_id, max=max_attempts)
            record = await result.single()
        state = record["state"] if record else "failed"
        if record and state == "failed":
            self._emit(
                "node_updated",
                node_id=node_id,
                node_type=record["label"],
                changes={"claim_state": "failed"},
            )
            logger.warning("work unit %s exhausted its attempts -> failed", node_id[:8])
        return state

    async def record_cost(
        self, node_id: str, tokens_in: int, tokens_out: int, llm_calls: int, elapsed_ms: float
    ) -> None:
        """Accumulate one episode's cost onto its work node. Atomic increment (no
        read-modify-write race; retries add up). Does NOT emit: this is evaluation
        bookkeeping, not a domain mutation - emitting node_updated would spuriously
        wake reactions (e.g. the Synthesizer on node_updated/Investigation)."""
        query = """
            MATCH (n {id: $id})
            SET n.tokens_in  = coalesce(n.tokens_in, 0)  + $tokens_in,
                n.tokens_out = coalesce(n.tokens_out, 0) + $tokens_out,
                n.llm_calls  = coalesce(n.llm_calls, 0)  + $llm_calls,
                n.elapsed_ms = coalesce(n.elapsed_ms, 0) + $elapsed_ms
        """
        async with self._driver.session() as session:
            await session.run(
                query,
                id=node_id,
                tokens_in=tokens_in,
                tokens_out=tokens_out,
                llm_calls=llm_calls,
                elapsed_ms=elapsed_ms,
            )

    async def recover_claimed(self, max_attempts: int) -> int:
        """Reset every node stuck in claim_state='claimed' back to 'pending' (or
        'failed' if it has exhausted its attempts), clearing the holder. Call once at
        startup: with no agents alive yet, any 'claimed' node is an orphan. Returns
        how many were touched."""
        query = """
            MATCH (n {claim_state: 'claimed'})
            WITH n, coalesce(n.attempts, 0) + 1 AS attempts
            SET n.attempts = attempts,
                n.claimed_by_agent_id = null,
                n.claim_state = CASE WHEN attempts >= $max THEN 'failed' ELSE 'pending' END
            RETURN count(n) AS recovered
        """
        async with self._driver.session() as session:
            result = await session.run(query, max=max_attempts)
            record = await result.single()
        return record["recovered"] if record else 0

    async def claim_case_for_synthesis(self) -> Case | None:
        query = """
            MATCH (c:Case {claim_state: 'pending'})
            WHERE NOT (c)-[:CONCLUDES]->(:Verdict)
              AND EXISTS { MATCH (h:Hypothesis {case_id: c.id}) }
              AND NOT EXISTS {
                MATCH (h:Hypothesis {case_id: c.id})
                WHERE coalesce(h.status, 'active') <> 'refuted'
                  AND NOT (h)-[:TESTS]->(:Investigation)
              }
              AND NOT EXISTS {
                MATCH (i:Investigation {case_id: c.id})
                WHERE NOT (i)-[:PRODUCES]->(:Evidence)
                  AND coalesce(i.status, '') <> 'skipped'
                  AND i.claim_state <> 'failed'
              }
              AND NOT EXISTS {
                MATCH (ev:Evidence {case_id: c.id})
                WHERE coalesce(ev.triaged, false) = false
              }
            WITH c LIMIT 1
            SET c.claim_state = 'claimed'
            RETURN c
        """
        async with self._claim_lock, self._driver.session() as session:
            result = await session.run(query)
            record = await result.single()
        return cast(Case, self._to_model(record["c"])) if record else None

    async def skip(self, node_id: str, reason: str) -> bool:
        """Terminally skip a work unit that is still PENDING, atomically: sets the
        domain outcome (status='skipped' + skip_reason) and claim_state='done' so no
        one claims it. Returns False if it was not pending anymore (already claimed,
        done or failed): an in-flight or finished unit is not silently discarded.
        EMITS node_updated: a skip is a domain outcome others react to (it can be
        the mutation that leaves a case quiescent)."""
        query = """
            MATCH (n {id: $id})
            WHERE n.claim_state = 'pending'
            SET n.status = 'skipped', n.skip_reason = $reason, n.claim_state = 'done'
            RETURN labels(n)[0] AS label
        """
        async with self._claim_lock, self._driver.session() as session:
            result = await session.run(query, id=node_id, reason=reason)
            record = await result.single()
        if record is not None:
            self._emit(
                "node_updated",
                node_id=node_id,
                node_type=record["label"],
                changes={"status": "skipped", "skip_reason": reason},
            )
            logger.info("skipped %s: %s", node_id[:8], reason)
        return record is not None

    async def create_suggested_hypothesis(
        self, hypothesis: Hypothesis, evidence_id: str, max_per_branch: int
    ) -> bool:
        """Create a GENERATED hypothesis, born connected (DERIVES from its Case and
        SUGGESTS from the evidence that inspired it), ONLY if its branch has room:
        the count and the create happen in one statement under the claim lock, so
        concurrent generations cannot exceed the cap. Counts every hypothesis of the
        branch INCLUDING refuted ones (exploring a dead line still spends budget).
        Returns False if the cap was hit (nothing created)."""
        props = hypothesis.model_dump(mode="json")
        query = """
            MATCH (c:Case {id: $case_id}), (e:Evidence {id: $evidence_id})
            OPTIONAL MATCH (b:Hypothesis {root_id: $root_id})
            WITH c, e, count(b) AS branch
            WHERE branch < $max
            CREATE (h:Hypothesis $props)
            CREATE (c)-[:DERIVES]->(h)
            CREATE (e)-[:SUGGESTS]->(h)
            RETURN h.id AS id
        """
        async with self._claim_lock, self._driver.session() as session:
            result = await session.run(
                query,
                case_id=hypothesis.case_id,
                evidence_id=evidence_id,
                root_id=hypothesis.root_id,
                max=max_per_branch,
                props=props,
            )
            record = await result.single()
        if record is None:
            return False  # branch full (or endpoints missing): nothing created
        self._emit("node_created", node_id=hypothesis.id, node_type="Hypothesis")
        self._emit(
            "edge_created", from_id=hypothesis.case_id, to_id=hypothesis.id, edge_type="DERIVES"
        )
        self._emit("edge_created", from_id=evidence_id, to_id=hypothesis.id, edge_type="SUGGESTS")
        return True

    async def get_full_graph(self) -> dict:
        """Every node and edge as plain dicts (the dashboard's connect snapshot).
        Visualization only: models are not needed, and unknown/legacy properties
        must survive as-is."""
        async with self._driver.session() as session:
            result = await session.run("MATCH (n) RETURN n")
            nodes = [
                {"label": list(record["n"].labels)[0], "props": dict(record["n"])}
                async for record in result
            ]
        async with self._driver.session() as session:
            result = await session.run(
                "MATCH (a)-[r]->(b) RETURN a.id AS source, type(r) AS type, b.id AS target"
            )
            edges = [dict(record) async for record in result]
        return {"nodes": nodes, "edges": edges}

    async def get_case_cost(self, case_id: str) -> dict:
        """Total spend of a case subgraph, for evaluation: token/call/time sums plus
        node count, over every case-scoped node AND the InputSignal that opened it
        (the open-case episode's cost lands on the signal, one OPENS hop out). Plain
        dict (like get_full_graph): it feeds metrics/dashboards, not role reasoning."""
        query = """
            MATCH (c:Case {id: $case_id})
            OPTIONAL MATCH (s:InputSignal)-[:OPENS]->(c)
            OPTIONAL MATCH (n {case_id: $case_id})
            WITH collect(DISTINCT n) + collect(DISTINCT s) AS nodes
            UNWIND nodes AS x
            RETURN count(x) AS node_count,
                   sum(coalesce(x.tokens_in, 0))  AS tokens_in,
                   sum(coalesce(x.tokens_out, 0)) AS tokens_out,
                   sum(coalesce(x.llm_calls, 0))  AS llm_calls,
                   sum(coalesce(x.elapsed_ms, 0)) AS elapsed_ms
        """
        async with self._driver.session() as session:
            result = await session.run(query, case_id=case_id)
            record = await result.single()
        if record is None:
            return {
                "node_count": 0,
                "tokens_in": 0,
                "tokens_out": 0,
                "llm_calls": 0,
                "elapsed_ms": 0.0,
            }
        return dict(record)

